spring:
  profiles: production
  application:
    name: spring-boot-mvc-demo

server:
  port: 8080
  context-path: /mvc

mysql:
  userName: root
  url: jdbc:mysql://127.0.0.1:3306/spring_boot_demo?useUnicode=true&characterEncoding=utf8&autoReconnect=true&failOverReadOnly=false


logging:
  file: spring-boot-mvc-demo.log
  path: ../logs/
  level:
    com.dragon.study.spring.boot: INFO