spring:
  application:
    name: spring-boot-demo
  boot:
    admin:
      url: http://192.168.2.203:8090

server:
  port: ${TEST_SERVER_PORT:8088}

person:
  monkey:
    name: monkey
    age: 2
    male: true
